WholesaleStore.Web/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using WholesaleStore.Core.IServices;
using WholesaleStore.Infrastructure.CustomFilters;
using WholesaleStore.Models.Filters;
using WholesaleStore.Models.Models;
using WholesaleStore.ViewModels.VMs;

namespace WholesaleStore.Web.Controllers
{
    public class CategoriesController : BaseController
    {
        private readonly ICategoryService _categoryService;
        private readonly ILogger<CategoriesController> _logger;

        public CategoriesController(ICategoryService categoryService, ILogger<CategoriesController> logger)
        {
            _categoryService = categoryService;
            _logger = logger;
        }

        [Authorize(Roles.SUPER_ADMIN)]
        public async Task<IActionResult> Index()
        {
            CategoryFilter filter = new CategoryFilter();

            List<CategoryModel> categories = await _categoryService.GetAllCategories();

            return View(categories);
        }

        public async Task<IActionResult> Create()
        {
            try
            {
                CategoryFilter categoryFilter = new CategoryFilter();
                categoryFilter.ParentCategoryId = 0;

                CategoryVM categoryVM = new CategoryVM();
                categoryVM.Category = new CategoryModel();

                categoryVM.MainCategories = await _categoryService.Get(categoryFilter);
                //categoryVM.Categories = await _categoryService.GetAllCategoriesWithSubCategories();
                return View(categoryVM);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(CategoryModel category)
        {
            try
            {
                bool succeded = await _categoryService.Add(category);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                throw;
            }
        }

        public async Task<IActionResult> ActivateCategory(int GategoryId)
        {
            //try
            //{
            //    bool succeded = await _seasonService.ActivateSeason(seasonId);
            //    if (!succeded) TempData["ErrorMsg"] = "Something wrong";
            //    return RedirectToAction("Index", new { schoolId = schoolId });
            //}
            //catch (Exception ex)
            //{
            //    throw;
            //}
            return RedirectToAction("Index");
        }
    }
}

WholesaleStore.Web/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Threading.Tasks;
using WholesaleStore.Core.IServices;
using WholesaleStore.Models.Filters;
using WholesaleStore.ViewModels.VMs;

namespace WholesaleStore.Web.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly ILogger<OrdersController> _logger;

        public OrdersController(IOrderService orderService, ILogger<OrdersController> logger)
        {
            _orderService = orderService;
            _logger = logger;
        }

        public async Task<IActionResult> Index(int storeId, int userId, Guid userGuid,
            int orderStatusId = -1, string paymentMethodName = "", decimal orderTotal = 0,
            DateTime? paidDate = null , DateTime? createdDate = null,
            int currentPage = 1, int maxRows = 2)
        {
            ViewData["MaxRows"] = maxRows;

            OrderVM orderVM = new OrderVM();
            orderVM.OrderFilter = new OrderFilter();
            orderVM.OrderFilter.CurrentPage = currentPage;
            orderVM.OrderFilter.MaxRows = maxRows;
            orderVM.OrderFilter.CreatedOnUtc = createdDate;
            orderVM.OrderFilter.PaidDateUtc = paidDate;
            orderVM.OrderFilter.StoreId = storeId;
            orderVM.OrderFilter.UserId = userId;
            orderVM.OrderFilter.UserGuid = userGuid;
            orderVM.OrderFilter.OrderStatusId = orderStatusId;
            orderVM.OrderFilter.PaymentMethodSystemName = paymentMethodName;
            orderVM.OrderFilter.OrderTotal = orderTotal;

            orderVM.Orders = await _orderService.Get(orderVM.OrderFilter);

            return View(orderVM);
        }
    }
}

WholesaleStore.Web/Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using WholesaleStore.Core.IServices;
using WholesaleStore.Infrastructure.CustomFilters;
using WholesaleStore.Models.Models;

namespace WholesaleStore.Web.Controllers
{
    public class StoreController : BaseController
    {
        private readonly IStoreService _storeService;
        private readonly IUserService _userService;

        public StoreController(IStoreService storeService, IUserService userService)
        {
            _storeService = storeService;
            _userService = userService;
        }

        [Authorize(Roles.SUPER_ADMIN)]
        public async Task<IActionResult> Index()
        {
            List<StoreModel> stores = await _storeService.Get(null);
            foreach (StoreModel store in stores)
            {
                store.AdminUser = await _userService.GetByID(store.AdminUserId);
            }
            return View(stores);
        }

        public IActionResult Create()
        {
            try
            {
                return View(new StoreModel());
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(StoreModel model)
        {
            try
            {
                model.CreatedDate = DateTime.Now;
                model.UpdatedDate = model.CreatedDate;

                await _storeService.Add(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public async Task<IActionResult> Edit(int storeId)
        {
            try
            {
                StoreModel store = await _storeService.GetByID(storeId);
                return View(store);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(StoreModel model)
        {
            try
            {
                model.UpdatedDate = DateTime.Now;

                bool updated = await _storeService.Update(model);

                if (!updated)
                    TempData["ErrorMsg"] = "لم يتم التعديل بنجاح";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public async Task<IActionResult> Delete(int storeId)
        {
            try
            {
                bool deleted = await _storeService.Delete(storeId);
                if (!deleted)
                    TempData["ErrorMsg"] = "لم يتم مسح المخزن بنجاح من فضلك حاول مرة اخري";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public async Task<IActionResult> ActivateStore(int storeId)
        {
            try
            {
                bool activated = await _storeService.ActivateStore(storeId);

                if (!activated)
                    TempData["ErrorMsg"] = "حدث خطأ ما برجاء المحاولة مرة اخري";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }
}

WholesaleStore.Web/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WholesaleStore.Core.IServices;
using WholesaleStore.Models.Filters;
using WholesaleStore.Models.Models;
using WholesaleStore.ViewModels.VMs;

namespace WholesaleStore.Web.Controllers
{
    public class UsersController : BaseController
    {
        private readonly IUserService _userService;
        private readonly IStoreService _storeService;

        public UsersController(IUserService userService, IStoreService storeService)
        {
            _userService = userService;
            _storeService = storeService;
        }

        public async Task<IActionResult> Index(
            string sortOrder, 
            string currentFilter, 
            string searchString, 
            int currentPage = 1, int maxRows = 3,
            string name = null, DateTime? created = null,
            int active = -1, int deleted = -1, string searchBtn = null)
        {
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["EmailSortParm"] = sortOrder == "Email" ? "email_desc" : "Email";

            UserVM userVM = new UserVM();
            userVM.UserFilter = new UserFilter();

            if (searchBtn != null && searchBtn == "Search")
            {
                userVM.UserFilter.CurrentPage = 1;
            }

            userVM.UserFilter.Name = name;
            userVM.UserFilter.CurrentPage = currentPage;
            userVM.UserFilter.MaxRows = maxRows;
            userVM.UserFilter.CreatedOnUtc = created;
            userVM.UserFilter.Active = active;
            userVM.UserFilter.Deleted = deleted;

            userVM.Users = await _userService.Get(userVM.UserFilter);

            userVM.Stores = await _storeService.GetAll();

            switch (sortOrder)
            {
                case "name_desc":
                    userVM.Users = userVM.Users.OrderByDescending(s => s.Username).ToList();
                    break;
                case "Email":
                    userVM.Users = userVM.Users.OrderBy(s => s.Email).ToList();
                    break;
                case "email_desc":
                    userVM.Users = userVM.Users.OrderByDescending(s => s.Email).ToList();
                    break;
                default:
                    userVM.Users = userVM.Users.OrderBy(s => s.Username).ToList();
                    break;
            }

            return View(userVM);
        }
    }
}

WholesaleStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - El Makhazen</title>

    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @*<div class="row me-auto"></div>*@

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">El Makhazen</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @*<partial name="_MainNav" />*@
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        <div class="row flex-nowrap">
            <partial name="_LeftSidebar" />
            <div class="col py-3">

                @if (!string.IsNullOrEmpty((string)TempData["ErrorMsg"]))
                {
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        @TempData["ErrorMsg"]
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                }

                <div class="container">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - El Makhazen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @*<div class="container">
        <main role="main" class="pb-3">
        @RenderBody()
        </main>
        </div>*@


    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>*@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/jquery.slim.min.js"></script>
    <script src="~/lib/popper.js/umd/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

WholesaleStore.Web/Views/Shared/_LeftSidebar.cshtml
@*<div class="container-fluid">
    <div class="row flex-nowrap">
    <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
    <span class="fs-5 d-none d-sm-inline">Menu</span>
    </a>
    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
    <li class="nav-item">
    <a href="#" class="nav-link align-middle px-0">
    <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
    </a>
    </li>
    <li>
    <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
    <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span>
    </a>
    <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
    <li class="w-100">
    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1 </a>
    </li>
    <li>
    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2 </a>
    </li>
    </ul>
    </li>
    <li>
    <a href="#" class="nav-link px-0 align-middle">
    <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Orders</span>
    </a>
    </li>
    <li>
    <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
    <i class="fs-4 bi-bootstrap"></i> <span class="ms-1 d-none d-sm-inline">Bootstrap</span>
    </a>
    <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
    <li class="w-100">
    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1</a>
    </li>
    <li>
    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2</a>
    </li>
    </ul>
    </li>
    <li>
    <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
    <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Products</span>
    </a>
    <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
    <li class="w-100">
    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 1</a>
    </li>
    <li>
    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 2</a>
    </li>
    <li>
    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 3</a>
    </li>
    <li>
    <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 4</a>
    </li>
    </ul>
    </li>
    <li>
    <a href="#" class="nav-link px-0 align-middle">
    <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Customers</span>
    </a>
    </li>
    </ul>
    <hr>
    <div class="dropdown pb-4">
    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
    <img src="https://github.com/mdo.png" alt="hugenerd" width="30" height="30" class="rounded-circle">
    <span class="d-none d-sm-inline mx-1">loser</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
    <li><a class="dropdown-item" href="#">New project...</a></li>
    <li><a class="dropdown-item" href="#">Settings</a></li>
    <li><a class="dropdown-item" href="#">Profile</a></li>
    <li>
    <hr class="dropdown-divider">
    </li>
    <li><a class="dropdown-item" href="#">Sign out</a></li>
    </ul>
    </div>
    </div>
    </div>
    </div>
    </div>*@

@using Microsoft.AspNetCore.Identity
@using WholesaleStore.Persistance.Data.Entities
@inject SignInManager<ApplicationUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-white border-right box-shadow">
        <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-dark min-vh-100">
            @*<a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                <span class="fs-5 d-none d-sm-inline">El Makhazen</span>
            </a>*@
            <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start text-right" id="menu">
                <li class="nav-item">
                    <a class="nav-link align-middle text-dark px-0" asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">الرئيسية</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link align-middle text-dark px-0" asp-area="" asp-controller="Users" asp-action="Index">
                        <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">المستخدمين</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link align-middle text-dark px-0" asp-area="" asp-controller="Store" asp-action="Index">
                        <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">المخازن</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link align-middle text-dark px-0" asp-area="" asp-controller="Categories" asp-action="Index">
                        <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">الأقسام</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link align-middle text-dark px-0" asp-area="" asp-controller="Orders" asp-action="Index">
                        <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">الطلبات</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
}
else
{

}

WholesaleStore.Web/Views/Shared/_MainNav.cshtml
<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">المخازن</a>
    </li>
</ul>