WholesaleStore.Web/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using WholesaleStore.Core.IServices;
using WholesaleStore.Models.Filters;
using WholesaleStore.Models.Models;
using WholesaleStore.ViewModels.VMs;

namespace WholesaleStore.Web.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly ILogger<ProductsController> _logger;

        public ProductsController(IProductService productService, ILogger<ProductsController> logger, ICategoryService categoryService)
        {
            _productService = productService;
            _logger = logger;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index(
            int storeId, string name = "",
            int stockQuantity = 0, decimal price = 0,
            decimal cost = 0, DateTime? created = null, DateTime? updated = null,
            int currentPage = 1, int maxRows = 2)
        {
            ViewData["MaxRows"] = maxRows;

            ProductVM productVM = new ProductVM();
            productVM.ProductFilter = new ProductFilter();
            productVM.ProductFilter.CurrentPage = currentPage;
            productVM.ProductFilter.MaxRows = maxRows;
            productVM.ProductFilter.StoreId = storeId;
            productVM.ProductFilter.Name = name;
            productVM.ProductFilter.StockQuantity = stockQuantity;
            productVM.ProductFilter.Price = price;
            productVM.ProductFilter.ProductCost = cost;
            productVM.ProductFilter.CreatedOnUtc = created;
            productVM.ProductFilter.UpdatedOnUtc = updated;

            productVM.Products = await _productService.Get(productVM.ProductFilter);

            return View(productVM);
        }

        public async Task<IActionResult> Create(int storeId)
        {
            try
            {
                ProductVM productVM = new ProductVM();
                productVM.Product = new ProductModel();
                productVM.Product.StoreId = storeId;
                productVM.Product.MainCategory = new CategoryModel();
                productVM.Categories = await _categoryService.GetAllCategoriesWithSubCategories();
                return View(productVM);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductVM productVM)
        {
            try
            {
                bool succeded = await _productService.Add(productVM.Product, productVM.Pictures, productVM.MainPicture);
                //if (!succeded)

                return RedirectToAction("Index", new { storeId = productVM.Product.StoreId });
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public async Task<List<CategoryModel>> GetChildCategories(int categoryId)
        {
            return await _categoryService.Get(new CategoryFilter() { ParentCategoryId = categoryId });
        }
    }
}

WholesaleStore.Web/Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using WholesaleStore.Core.IServices;
using WholesaleStore.Infrastructure.CustomFilters;
using WholesaleStore.Models.Models;

namespace WholesaleStore.Web.Controllers
{
    public class StoreController : BaseController
    {
        private readonly IStoreService _storeService;
        private readonly IUserService _userService;

        public StoreController(IStoreService storeService, IUserService userService)
        {
            _storeService = storeService;
            _userService = userService;
        }

        [Authorize(Roles.SUPER_ADMIN)]
        public async Task<IActionResult> Index()
        {
            List<StoreModel> stores = await _storeService.Get(null);
            foreach (StoreModel store in stores)
            {
                store.AdminUser = await _userService.GetByID(store.AdminUserId);
            }
            return View(stores);
        }

        public IActionResult Create()
        {
            try
            {
                return View(new StoreModel());
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(StoreModel model)
        {
            try
            {
                model.CreatedDate = DateTime.Now;
                model.UpdatedDate = model.CreatedDate;

                await _storeService.Add(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public async Task<IActionResult> Edit(int storeId)
        {
            try
            {
                StoreModel store = await _storeService.GetByID(storeId);
                return View(store);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(StoreModel model)
        {
            try
            {
                model.UpdatedDate = DateTime.Now;

                bool updated = await _storeService.Update(model);

                if (!updated)
                    TempData["ErrorMsg"] = "لم يتم التعديل بنجاح";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public async Task<IActionResult> Delete(int storeId)
        {
            try
            {
                bool deleted = await _storeService.Delete(storeId);
                if (!deleted)
                    TempData["ErrorMsg"] = "لم يتم مسح المخزن بنجاح من فضلك حاول مرة اخري";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public async Task<IActionResult> ActivateStore(int storeId)
        {
            try
            {
                bool activated = await _storeService.ActivateStore(storeId);

                if (!activated)
                    TempData["ErrorMsg"] = "حدث خطأ ما برجاء المحاولة مرة اخري";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }
}

WholesaleStore.Web/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WholesaleStore.Core.IServices;
using WholesaleStore.Models.Filters;
using WholesaleStore.Models.Models;
using WholesaleStore.ViewModels.VMs;

namespace WholesaleStore.Web.Controllers
{
    public class UsersController : BaseController
    {
        private readonly IUserService _userService;
        private readonly IStoreService _storeService;

        public UsersController(IUserService userService, IStoreService storeService)
        {
            _userService = userService;
            _storeService = storeService;
        }

        public async Task<IActionResult> Index(
            string sortOrder, 
            string currentFilter, 
            string searchString, 
            int currentPage = 1, int maxRows = 3,
            string name = null, DateTime? created = null,
            int active = -1, int deleted = -1, string searchBtn = null)
        {
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["EmailSortParm"] = sortOrder == "Email" ? "email_desc" : "Email";

            UserVM userVM = new UserVM();
            userVM.UserFilter = new UserFilter();

            if (searchBtn != null && searchBtn == "Search")
            {
                userVM.UserFilter.CurrentPage = 1;
            }

            userVM.UserFilter.Name = name;
            userVM.UserFilter.CurrentPage = currentPage;
            userVM.UserFilter.MaxRows = maxRows;
            userVM.UserFilter.CreatedOnUtc = created;
            userVM.UserFilter.Active = active;
            userVM.UserFilter.Deleted = deleted;

            userVM.Users = await _userService.Get(userVM.UserFilter);

            userVM.Stores = await _storeService.GetAll();

            switch (sortOrder)
            {
                case "name_desc":
                    userVM.Users = userVM.Users.OrderByDescending(s => s.Username).ToList();
                    break;
                case "Email":
                    userVM.Users = userVM.Users.OrderBy(s => s.Email).ToList();
                    break;
                case "email_desc":
                    userVM.Users = userVM.Users.OrderByDescending(s => s.Email).ToList();
                    break;
                default:
                    userVM.Users = userVM.Users.OrderBy(s => s.Username).ToList();
                    break;
            }

            return View(userVM);
        }
    }
}

WholesaleStore.Web/Views/Store/Create.cshtml
@model WholesaleStore.Models.Models.StoreModel

@{
    ViewData["Title"] = "انشاء مخزن";
}

@if (!string.IsNullOrEmpty((string)ViewData["Error"]))
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @ViewData["Error"].ToString();
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<hr />
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4 text-right">
        <h1>انشاء مخزن جديد</h1>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">الاسم</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyAddress" class="control-label">العنوان</label>
                <input asp-for="CompanyAddress" class="form-control" />
                <span asp-validation-for="CompanyAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyPhoneNumber" class="control-label">رقم الهاتف</label>
                <input asp-for="CompanyPhoneNumber" class="form-control" />
                <span asp-validation-for="CompanyPhoneNumber" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="CreatedDate" class="control-label">تاريخ الانشاء</label>
                <input type="date" asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <div class="form-check form-switch">
                    <input type="checkbox" asp-for="Active" class="form-check-input" />
                    <label asp-for="Active" class="form-check-label">مفعل</label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="انشاء" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-12 text-right">
        <a asp-action="Index">عودة الي القائمة</a>
    </div>
</div>
@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}  

WholesaleStore.Web/Views/Store/Edit.cshtml
@model WholesaleStore.Models.Models.StoreModel

@{
    ViewData["Title"] = "Edit";
}
<hr />
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4 text-right">
        <h1>تعديل علي المخزن</h1>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @Html.HiddenFor(a => a.CreatedDate, Model.CreatedDate)
                @Html.HiddenFor(a => a.Id, Model.Id)
                <label asp-for="Id" class="control-label">مخزن رقم</label>
                <input value="@Model.Id" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">الاسم</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyAddress" class="control-label">العنوان</label>
                <input asp-for="CompanyAddress" class="form-control" />
                <span asp-validation-for="CompanyAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyPhoneNumber" class="control-label">رقم الهاتف</label>
                <input asp-for="CompanyPhoneNumber" class="form-control" />
                <span asp-validation-for="CompanyPhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="form-check form-switch">
                    <input type="checkbox" asp-for="Active" class="form-check-input" />
                    <label asp-for="Active" class="form-check-label">مفعل</label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="تعديل" class="btn btn-primary" />
            </div>
        </form>

        <div>
            <a asp-action="Index">عودة الي القائمة</a>
        </div>
    </div>
</div>
@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}  

WholesaleStore.Web/Views/Store/Index.cshtml
@model IEnumerable<WholesaleStore.Models.Models.StoreModel>
@{
    ViewData["Title"] = "Index";
}

<div class="text-center">
    <h1 class="display-4">المخازن</h1>
    <p>يمكنك ادارة المخازن من هذه الشاشة</p>
</div>

<div class="row">
    <div class="col-12">
        &nbsp;
    </div>
</div>


<div class="row">
    <div class="col-md-12 text-right">
        <a asp-action="Create">اضافة مخزن جديد</a>
    </div>
</div>

<table class="table table-striped table-bordered text-right">
    <thead>
        <tr>
            <td></td>
            <td>الموظف المسؤول</td>
            <td>مفعل</td>
            <td>تاريخ الانشاء</td>
            <td>رقم التليفون</td>
            <td>العنوان</td>
            <td>اسم المخزن</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var store in Model)
        {
            <tr>
                <td>
                    <a class="btn btn-success" asp-action="Index" asp-controller="Products"
                   asp-route-storeId="@store.Id">المنتجات</a>

                    <a class="btn btn-info" asp-action="Edit" asp-controller="Store"
                   asp-route-storeId="@store.Id">تعديل</a>

                    <a class="btn btn-danger" asp-action="Delete" asp-controller="Store"
                   asp-route-storeId="@store.Id"
                   onclick="return confirm('هل انت متأكد من حذف @store.Name ؟')">حذف</a>
                </td>
                <td>
                    @if (store.AdminUser != null)
                    {
                        <a class="btn btn-info" asp-action="View" asp-controller="Users"
                        asp-route-governorateId="@store.Id">@store.AdminUser.Username</a>
                    }
                    else
                    {
                        <span class="text-center">---</span>
                    }
                </td>
                <td>
                    @{
                        var url = Url.Action("ActivateStore", "Store", new { storeId = store.Id }, null);
                    }
                    <div class="form-check form-switch">
                        @Html.CheckBoxFor(m => store.Active, new { @class = "form-check-input", @id = "flexSwitchCheckDefault", onclick = "window.location = '" + url + "'" })
                        <label class="form-check-label" for="flexSwitchCheckDefault"></label>
                    </div>
                </td>
                @* <td>
                    <div class="form-check form-switch">
                    <form asp-action="ActivateStore" asp-controller="Store"
                    asp-route-isActive="@store.Active" method="post">
                    <input type="checkbox" asp-for="@store.Active" class="form-check-input" id="super-admin-chk"
                    onclick="this.form.submit();" />
                    </form>
                    </div>
                    </td>*@
                <td>@store.CreatedDate.ToString("MM/dd/yyyy")</td>
                <td>@store.CompanyPhoneNumber</td>
                <td>@store.CompanyAddress</td>
                <td>@store.Name</td>
            </tr>

        }
    </tbody>
</table> 